### ISSUE TITLE
Error - Produce failed: Local: Unkown topic (empty)

### ISSUE THREAD

**Issue by Allifiando** [g-clef/KafkaLogger#5]
i got this error when deploy my bro with your basic policy 

```
1518521505.526608	Reporter::ERROR	Produce failed: Local: Unknown topic	(empty)
1518521505.526608	Reporter::ERROR	failed line: {"timestamp":"1518521168888","uid":"CI3xfW1wjKR8xSLgBb","source_ip":"10.252.108.86","source_port":42416,"dest_ip":"23.51.43.27","dest_port":80,"proto":"tcp","duration":35.712619,"orig_bytes":1,"resp_bytes":0,"conn_state":"SF","local_orig":true,"local_resp":false,"missed_bytes":0,"history":"AafF","orig_pkts":5,"orig_ip_bytes":260,"resp_pkts":6,"resp_ip_bytes":312,"tunnel_parents":[],"sensor":"brosensor","type":"conn"}	(empty)
```

those are in reporter.log when i try to deploy  , can you help my to fix this problem ?

**Comment by g-clef** [comment]
It looks like you haven't specified a kafka topic in the bro config files. 
You have to tell bro which topic in kafka it's supposed to write to. (If the topic you specify doesn't exist on the Kafka server, you'll get a similar error, but it should say the topic name instead of "(empty)" )

**Comment by g-clef** [comment]
Closing for now. Feel free to re-open if you still see this after setting that config.
